import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { Toaster } from "@/components/ui/toaster"
import Sidebar from "./components/Sidebar";
import Provider from "./components/Provider";

import AppHeader from "./components/AppHeader";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <SidebarProvider>
            <Sidebar />
            <SidebarInset>
            <AppHeader />
            {children}
            </SidebarInset>
            
          </SidebarProvider>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
